### ISSUE TITLE
Add doc string to operations methods

### ISSUE THREAD

**Issue by granrothge** [mcvine/mcvine#294]
operations.translate?
Signature: operations.translate(shape, **kwds)
Docstring: <no docstring>
File:      ~/anaconda/envs/mcvine/lib/python2.7/site-packages/instrument/geometry/operations.py
Type:      function

**Comment by yxqd** [comment]
@granrothge working on it now. Will take a bit time to be available at conda. For now, you can see the doc at https://github.com/danse-inelastic/instrument/blob/0fe0522cf90f60261ed3129275d8b0f542ae0ed6/instrument/geometry/operations.py#L47
