### ISSUE TITLE
Update laz.py to work more generally

### ISSUE THREAD

**Issue by granrothge** [mcvine/mcvine#304]
the `#CELL` line should be able to be anywhere in the file

**Comment by yxqd** [comment]
Refs: 
* https://github.com/mcvine/mcvine/blob/master/packages/mccomponents/python/mccomponents/sample/diffraction/parsers/laz.py
* https://github.com/mcvine/mcvine/blob/cc1e00205167a5679660defdf8e67c0fa65a6785/packages/mccomponents/tests/data/Al.laz

**Comment by granrothge** [comment]
I'll add another laz file.  Also I am updating the cross section parser too.

**Comment by granrothge** [comment]
the mcstas cif2hkl works pretty well I think.
